# sheldon: zsh
# ---
# See https://github.com/rossmacarthur/sheldon

shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
defer-more = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -t 0.5 source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-settings]
inline = '''
unsetopt extendedglob
setopt nomatch notify nobgnice
setopt autocd autopushd pushdignoredups pushdsilent pushdtohome
setopt histfindnodups histignoredups histignorespace histverify sharehistory
setopt interactivecomments noclobber longlistjobs

# Keybindings
export KEYTIMEOUT=1
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
'''

[plugins.vi-mode]
local = "~/.config/zsh"
use = [ "vi-cursor.zsh" ]
	[plugins.vi-mode.hooks]
	# Enable readline vi-mode for myself only
	# See ./functions.d/ssh.bash for implementation
	pre = '''
	if [ "${LC_IDENTIFICATION:-$USER}" = rafi ] \
		|| [[ "${LC_IDENTIFICATION:-$USER}" == rafael* ]]
	then
		set -o vi
	fi
	'''

[plugins.aliases]
local = "~/.config/bash"
use = [ "aliases" ]

# Prompt themes
# ---

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

# FRAMEWORKS
# ---

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
	[plugins.zsh-history-substring-search.hooks]
	post = '''
	bindkey -M emacs '^P' history-substring-search-up
	bindkey -M emacs '^N' history-substring-search-down
	bindkey -M viins '^P' history-substring-search-up
	bindkey -M viins '^N' history-substring-search-down
	'''

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer-more"]

[plugins.zsh-dircolors-solarized]
github = "joel-porquet/zsh-dircolors-solarized"
use = ["zsh-dircolors-solarized.zsh"]
apply = ["defer-more"]

# PRODUCTIVITY
# ---

[plugins.zoxide]
inline = '''
if hash zoxide 2>/dev/null; then
	export _ZO_ECHO=1
	export _ZO_DATA_DIR="$XDG_CACHE_HOME/zoxide"
	eval "$(zoxide init zsh)"
fi
'''

[plugins.pyenv]
# Work with multiple versions of Python via https://github.com/pyenv/pyenv
# But don't overcast shims when inside an activated virtualenv sub-shell.
inline = '''
if [ -z "$VIRTUAL_ENV" ] && hash pyenv 2>/dev/null; then
	export PYENV_ROOT="${XDG_DATA_HOME}/python/pyenv"
	export PYENV_VIRTUALENV_DISABLE_PROMPT=1
	eval "$(pyenv init --no-push-path -)"
fi
'''

[plugins.forgit]
	github = "wfxr/forgit"
	dir = "bin"
	apply = ["PATH"]
	[plugins.forgit.hooks]
		post = "export -r FORGIT_NO_ALIASES=1"

# COMPLETIONS
# ---

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'
